name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install .NET WebAssembly Tools
      run: dotnet workload install wasm-tools

    - name: Publish with GitHub Pages Support
      run: dotnet publish src/Selmir.MudGridify.Playground/Selmir.MudGridify.Playground.csproj -c:Release -o:publish -p:GHPages=true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: publish/wwwroot
        force_orphan: true
